CREATE TABLE IF NOT EXISTS `users` (
  ID INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  pw_hash VARCHAR(255) NOT NULL,
  UNIQUE KEY unique_username(username),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `categories` (
  ID INT NOT NULL AUTO_INCREMENT,
  category_name varchar(100),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `questions` (
  ID INT NOT NULL AUTO_INCREMENT,
  question TEXT NOT NULL,
  categoryID INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (categoryID) REFERENCES categories(ID)
);

CREATE TABLE IF NOT EXISTS `answers` (
  ID INT NOT NULL AUTO_INCREMENT,
  answer TEXT NOT NULL,
  correct TINYINT(1) NOT NULL,
  questionID INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (questionID) REFERENCES questions(ID)
);

CREATE TABLE IF NOT EXISTS `results`(
  ID INT NOT NULL AUTO_INCREMENT,
  userID INT NOT NULL,
  questionID INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FOREIGN KEY (userID) REFERENCES users(ID),
  CONSTRAINT FOREIGN KEY (questionID) REFERENCES questions(ID)
);

