# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "username": "WOH",
  "password" : "P@ssw0rd"
}

###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "WOH",
  "password" : "P@ssw0rd"
}

###

GET http://localhost:4000/api/category
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lc3RhbXAiOjEyMzEyMywidXNlcm5hbWUiOiJXT0gifQ.-rN3Pz0nniFcS-jM8CaXjVJsWr3Kxj3KH3qTGh4p7vc


###

POST http://localhost:4000/api/category/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lc3RhbXAiOjEyMzEyMywidXNlcm5hbWUiOiJXT0gifQ.-rN3Pz0nniFcS-jM8CaXjVJsWr3Kxj3KH3qTGh4p7vc
Content-Type: application/json

{
"category_name": "Zichen"
}


###

PUT http://localhost:4000/api/category/2/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lc3RhbXAiOjEyMzEyMywidXNlcm5hbWUiOiJEYXZpZCJ9.2iypOTd_0zQqcGs1RS7N-6bbyRxoIQxx4rOcZjxtjPU
Content-Type: application/json

{
  "category_name": "Schnaps"
}

###


DELETE http://localhost:4000/api/category/1/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lc3RhbXAiOjEyMzEyMywidXNlcm5hbWUiOiJEYXZpZCJ9.2iypOTd_0zQqcGs1RS7N-6bbyRxoIQxx4rOcZjxtjPU
Content-Type: application/json


###

###

GET http://localhost:4000/api/question
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lc3RhbXAiOjEyMzEyMywidXNlcm5hbWUiOiJEb21pbmlrIn0.26rU3HOPbZiAPUeUXNxwhXlRMP9zAul3QEsViiZTpMg


###

POST http://localhost:4000/api/question/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lc3RhbXAiOjEyMzEyMywidXNlcm5hbWUiOiJXT0gifQ.-rN3Pz0nniFcS-jM8CaXjVJsWr3Kxj3KH3qTGh4p7vc
Content-Type: application/json

{
  "question": "DefreggerZichen?",
  "category_id": 1,
  "answers": [
              {
                "answer": "ja",
                "correct": true
              },
              {
                "answer": "nein",
                "correct": false
              }
             ]
}

###
###
GET http://localhost:4000/api/question/category/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lc3RhbXAiOjEyMzEyMywidXNlcm5hbWUiOiJXT0gifQ.-rN3Pz0nniFcS-jM8CaXjVJsWr3Kxj3KH3qTGh4p7vc
Content-Type: application/json

###